[package]
name = "bfxrs"
version = "0.0.1"
authors = ["rjmacarthy <richardmacarthy@hotmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"

[lib]
name = "bfxrs"
path = "src/lib.rs"
